/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_final_edd1;

import java.awt.List;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Darwin
 */
public class JugarMayor extends javax.swing.JFrame {

    int turno = 1;
    int dadoJ1 = 0, dadoJ2 = 0, dadoJ3 = 0, dadoJ4 = 0;

    /**
     * Creates new form JugarMayor
     */
    public JugarMayor() {
        initComponents();
        setLocationRelativeTo(null);
        switch (Variables.njugadores) {
            case 2:
                jLabelJ3.setVisible(false);
                jLabelJ4.setVisible(false);
                break;
            case 3:
                jLabelJ4.setVisible(false);
                break;
        }
        transparenciaButton();
    }
    @SuppressWarnings("unchecked")
    public void transparenciaButton() {
        dadosbtn.setOpaque(false);
        dadosbtn.setContentAreaFilled(false);
        dadosbtn.setBorderPainted(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        dadosbtn = new javax.swing.JButton();
        LabelJ1 = new javax.swing.JLabel();
        LabelJ2 = new javax.swing.JLabel();
        jLabelJ3 = new javax.swing.JLabel();
        jLabelJ4 = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        Titulo.setText("TURNO DEL JUGADOR ROJO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 350, 30));

        dadosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosbtnActionPerformed(evt);
            }
        });
        getContentPane().add(dadosbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 140, 50));

        LabelJ1.setBackground(new java.awt.Color(0, 0, 0));
        LabelJ1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        LabelJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data1/Jrojo.png"))); // NOI18N
        LabelJ1.setText("0");
        getContentPane().add(LabelJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 250, 30));

        LabelJ2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        LabelJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data1/Jamarillo.png"))); // NOI18N
        LabelJ2.setText("0");
        getContentPane().add(LabelJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 240, 20));

        jLabelJ3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabelJ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data1/Jverde.png"))); // NOI18N
        jLabelJ3.setText("0");
        getContentPane().add(jLabelJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 240, -1));

        jLabelJ4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabelJ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data1/Jazul.png"))); // NOI18N
        jLabelJ4.setText("0");
        getContentPane().add(jLabelJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 240, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data1/JugadorMayor.png"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosbtnActionPerformed
        // TODO add your handling code here:

        int dado1;//dado 1
        int dado2;//dado2
        int dado;

        switch (turno) {
            case 1:
                dado1 = (int) ((Math.random()) * 60 / 10) + 1;//dado 1
                dado2 = (int) ((Math.random()) * 60 / 10) + 1;//dado2
                dado = dado1 + dado2;
                dados(dado1, dado2);
                dadoJ1 = dado;
                LabelJ1.setText(""+dado);
                Titulo.setText("TURNO DEL JUGADOR AMARILLO");
                break;

            case 2:

                do {
                    dado1 = (int) ((Math.random()) * 60 / 10) + 1;//dado 1
                    dado2 = (int) ((Math.random()) * 60 / 10) + 1;//dado2
                    dado = dado1 + dado2;
                } while (dadoJ1 == dado);

                dados(dado1, dado2);
                dadoJ2 = dado;
                LabelJ2.setText("" + dado);
                if (turno != Variables.njugadores){
                    Titulo.setText("TURNO DEL JUGADOR VERDE");
                }
                
                break;
            case 3:

                do {
                    dado1 = (int) ((Math.random()) * 60 / 10) + 1;//dado 1
                    dado2 = (int) ((Math.random()) * 60 / 10) + 1;//dado2
                    dado = dado1 + dado2;
                } while (dadoJ1 == dado || dadoJ2 == dado);

                dados(dado1, dado2);
                dadoJ3 = dado;
                jLabelJ3.setText("" + dado);
                if (turno != Variables.njugadores){
                    Titulo.setText("TURNO DEL JUGADOR AZUL");
                }
                
                break;
            case 4:

                do {
                    dado1 = (int) ((Math.random()) * 60 / 10) + 1;//dado 1
                    dado2 = (int) ((Math.random()) * 60 / 10) + 1;//dado2
                    dado = dado1 + dado2;
                } while (dadoJ1 == dado || dadoJ2 == dado || dadoJ3 == dado);

                dados(dado1, dado2);
                dadoJ4 = dado;
                jLabelJ4.setText("" + dado);
                break;
        }
        turno++;

        //Hacer validación si son iguales
        if (turno > Variables.njugadores) {

            switch (Variables.njugadores) {
                case 2:
                    if (dadoJ1 > dadoJ2) {
                        Variables.jugador1.turno = 1;
                        Variables.jugador2.turno = 2;
                    } else {
                        Variables.jugador1.turno = 2;
                        Variables.jugador2.turno = 1;
                    }
                    Variables.vecTurnos[0] = Variables.jugador1.turno;
                    Variables.vecTurnos[1] = Variables.jugador2.turno;
                    JOptionPane.showMessageDialog(null, "Jugador Rojo empieza de: " + Variables.jugador1.turno + "\n"
                            + "Jugador Amarillo empieza de: " + Variables.jugador2.turno,
                            "Resultados", JOptionPane.PLAIN_MESSAGE);
                    new Interfaz().setVisible(true);
                    this.dispose();
                    break;
                case 3:
                    
                    if (dadoJ1 > dadoJ2 && dadoJ1 > dadoJ3) {
                        Variables.jugador1.turno = 1;
                        if (dadoJ2 > dadoJ3) {
                            Variables.jugador2.turno = 2;
                            Variables.jugador3.turno = 3;
                        } else {
                            Variables.jugador2.turno = 3;
                            Variables.jugador3.turno = 2;
                        }
                    }
                    if (dadoJ2 > dadoJ1 && dadoJ2 > dadoJ3) {
                        Variables.jugador2.turno = 1;
                        if (dadoJ1 > dadoJ3) {
                            Variables.jugador1.turno = 2;
                            Variables.jugador3.turno = 3;
                        } else {
                            Variables.jugador1.turno = 3;
                            Variables.jugador3.turno = 2;
                        }
                    }
                    if (dadoJ3 > dadoJ1 && dadoJ3 > dadoJ2) {
                        Variables.jugador3.turno = 1;
                        if (dadoJ1 > dadoJ2) {
                            Variables.jugador1.turno = 2;
                            Variables.jugador2.turno = 3;
                        } else {
                            Variables.jugador1.turno = 3;
                            Variables.jugador2.turno = 2;
                        }
                    }
                    Variables.vecTurnos[0] = Variables.jugador1.turno;
                    Variables.vecTurnos[1] = Variables.jugador2.turno;
                    Variables.vecTurnos[2] = Variables.jugador3.turno;
                    JOptionPane.showMessageDialog(null, "Jugador Rojo empieza de: " + Variables.jugador1.turno + "\n"
                            + "Jugador Amarillo empieza de: " + Variables.jugador2.turno + "\n"
                            + "Jugador Verde empieza de: " + Variables.jugador3.turno,
                            "Resultados", JOptionPane.PLAIN_MESSAGE);
                    new Interfaz().setVisible(true);
                    this.dispose();
                    break;
                case 4:
                    
                    if (dadoJ1 > dadoJ2 && dadoJ1 > dadoJ3 && dadoJ1 > dadoJ4) { //uno primer jugador
                        Variables.jugador1.turno = 1;
                        if (dadoJ2 > dadoJ3 && dadoJ2 > dadoJ4) {//dos segundo jugador
                            Variables.jugador2.turno = 2;
                            if (dadoJ3 > dadoJ4) {//tres y 4
                                Variables.jugador3.turno = 3;
                                Variables.jugador4.turno = 4;
                            } else {
                                Variables.jugador3.turno = 4;
                                Variables.jugador4.turno = 3;
                            }
                        }
                        if (dadoJ3 > dadoJ2 && dadoJ3 > dadoJ4) {//tres segundo jugador
                            Variables.jugador3.turno = 2;
                            if (dadoJ2 > dadoJ4) { //dos y cuatro
                                Variables.jugador2.turno = 3;
                                Variables.jugador4.turno = 4;
                            } else {
                                Variables.jugador2.turno = 4;
                                Variables.jugador4.turno = 3;
                            }
                        }
                        if (dadoJ4 > dadoJ2 && dadoJ4 > dadoJ3) {//Cuatro segundo jugador
                            Variables.jugador4.turno = 2;
                            if (dadoJ2 > dadoJ3) { //dos y tres
                                Variables.jugador2.turno = 3;
                                Variables.jugador3.turno = 4;
                            } else {
                                Variables.jugador2.turno = 4;
                                Variables.jugador3.turno = 3;
                            }
                        }
                    }
                    if (dadoJ2 > dadoJ1 && dadoJ2 > dadoJ3 && dadoJ2 > dadoJ4) { //Dos primer jugador
                        Variables.jugador2.turno = 1;
                        if (dadoJ1 > dadoJ3 && dadoJ1 > dadoJ4) { //Uno segundo jugador
                            Variables.jugador1.turno = 2;
                            if (dadoJ3 > dadoJ4) { //tres y cuatro
                                Variables.jugador3.turno = 3;
                                Variables.jugador4.turno = 4;
                            } else {
                                Variables.jugador3.turno = 4;
                                Variables.jugador4.turno = 3;
                            }
                        }
                        if (dadoJ3 > dadoJ1 && dadoJ3 > dadoJ4) { //tres segundo jugador
                            Variables.jugador3.turno = 2;
                            if (dadoJ1 > dadoJ4) { //uno y cuatro
                                Variables.jugador1.turno = 3;
                                Variables.jugador4.turno = 4;
                            } else {
                                Variables.jugador1.turno = 4;
                                Variables.jugador4.turno = 3;
                            }
                        }
                        if (dadoJ4 > dadoJ1 && dadoJ4 > dadoJ3) { //cuatro segundo jugador
                            Variables.jugador4.turno = 2;
                            if (dadoJ1 > dadoJ3) { //uno y tres
                                Variables.jugador1.turno = 3;
                                Variables.jugador3.turno = 4;
                            } else {
                                Variables.jugador1.turno = 4;
                                Variables.jugador3.turno = 3;
                            }
                        }
                    }
                    if (dadoJ3 > dadoJ1 && dadoJ3 > dadoJ2 && dadoJ3 > dadoJ4) { //tres primer jugador
                        Variables.jugador3.turno = 1;
                        if (dadoJ1 > dadoJ2 && dadoJ1 > dadoJ4) {//uno segundo jugador
                            Variables.jugador1.turno = 2;
                            if (dadoJ2 > dadoJ4) { //dos y cuatro
                                Variables.jugador2.turno = 3;
                                Variables.jugador4.turno = 4;
                            } else {
                                Variables.jugador2.turno = 4;
                                Variables.jugador4.turno = 3;
                            }
                        }
                        if (dadoJ2 > dadoJ1 && dadoJ2 > dadoJ4) { //dos segundo jugador
                            Variables.jugador2.turno = 2;
                            if (dadoJ1 > dadoJ4) { //uno y cuatro
                                Variables.jugador1.turno = 3;
                                Variables.jugador4.turno = 4;
                            } else {
                                Variables.jugador1.turno = 4;
                                Variables.jugador4.turno = 3;
                            }
                        }
                        if (dadoJ4 > dadoJ1 && dadoJ4 > dadoJ2) { //cuatro segundo jugador
                            Variables.jugador4.turno = 2;
                            if (dadoJ1 > dadoJ2) {//uno y dos
                                Variables.jugador1.turno = 3;
                                Variables.jugador2.turno = 4;
                            } else {
                                Variables.jugador1.turno = 4;
                                Variables.jugador2.turno = 3;
                            }
                        }
                    }
                    if (dadoJ4 > dadoJ1 && dadoJ4 > dadoJ2 && dadoJ4 > dadoJ3) { //cuatro primer jugador
                        Variables.jugador4.turno = 1;
                        if (dadoJ1 > dadoJ2 && dadoJ1 > dadoJ3) { //uno segundo jugador
                            Variables.jugador1.turno = 2;
                            if (dadoJ2 > dadoJ3) { //dos y tres
                                Variables.jugador2.turno = 3;
                                Variables.jugador3.turno = 4;
                            } else {
                                Variables.jugador2.turno = 4;
                                Variables.jugador3.turno = 3;
                            }
                        }
                        if (dadoJ2 > dadoJ1 && dadoJ2 > dadoJ3) { //dos segundo jugador
                            Variables.jugador2.turno = 2;
                            if (dadoJ1 > dadoJ3) { //uno y tres
                                Variables.jugador1.turno = 3;
                                Variables.jugador3.turno = 4;
                            } else {
                                Variables.jugador1.turno = 4;
                                Variables.jugador3.turno = 3;
                            }
                        }
                        if (dadoJ3 > dadoJ1 && dadoJ3 > dadoJ2) { //tres segundo jugador
                            Variables.jugador3.turno = 2;
                            if (dadoJ1 > dadoJ2) {//uno y dos
                                Variables.jugador1.turno = 3;
                                Variables.jugador2.turno = 4;
                            } else {
                                Variables.jugador1.turno = 4;
                                Variables.jugador2.turno = 3;
                            }
                        }
                    }
                    Variables.vecTurnos[0] = Variables.jugador1.turno;
                    Variables.vecTurnos[1] = Variables.jugador2.turno;
                    Variables.vecTurnos[2] = Variables.jugador3.turno;
                    Variables.vecTurnos[3] = Variables.jugador4.turno;
                    JOptionPane.showMessageDialog(null, "Jugador Rojo empieza de: " + Variables.jugador1.turno + "\n"
                            + "Jugador Amarillo empieza de: " + Variables.jugador2.turno + "\n"
                            + "Jugador Verde empieza de: " + Variables.jugador3.turno + "\n"
                            + "Jugador Azul empieza de: " + Variables.jugador4.turno,
                            "Resultados", JOptionPane.PLAIN_MESSAGE);
                    new Interfaz().setVisible(true);
                    this.dispose();
                    break;
            }

        }

    }//GEN-LAST:event_dadosbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugarMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugarMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugarMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugarMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JugarMayor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelJ1;
    private javax.swing.JLabel LabelJ2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton dadosbtn;
    private javax.swing.JLabel jLabelJ3;
    private javax.swing.JLabel jLabelJ4;
    private javax.swing.JLabel jLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
    public void dados(int dado1, int dado2) {
        ImageIcon icono = null;

        switch (dado1) { // ver las combinaciones 
            case 1:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/1,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/1,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/1,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/1,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/1,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/1,6.png"));
                        break;
                }
                break;
            case 2:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/2,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/2,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/2,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/2,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/2,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/2,6.png"));
                        break;
                }
                break;
            case 3:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/3,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/3,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/3,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/3,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/3,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/3,6.png"));
                        break;
                }
                break;
            case 4:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/4,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/4,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/4,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/4,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/4,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/4,6.png"));
                        break;
                }
                break;
            case 5:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/5,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/5,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/5,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/5,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/5,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/5,6.png"));
                        break;
                }
                break;
            case 6:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/6,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/6,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/6,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/6,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/6,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/6,6.png"));
                        break;
                }
                break;
        }
        JOptionPane.showMessageDialog(null, "", "DADOS", JOptionPane.PLAIN_MESSAGE, icono);
    }

}
