/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_final_edd1;

import java.awt.List;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Darwin
 */
public class JugarMayor extends javax.swing.JFrame {
   
    int turno = 1;

    /**
     * Creates new form JugarMayor
     */
    public JugarMayor() {
        initComponents();
        Variables.njugadores = 3;
        switch (Variables.njugadores) {
            case 2:
                jLabelJ3.setVisible(false);
                jLabelJ4.setVisible(false);
                break;
            case 3:
                jLabelJ4.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        dadosbtn = new javax.swing.JButton();
        LabelJ1 = new javax.swing.JLabel();
        LabelJ2 = new javax.swing.JLabel();
        jLabelJ3 = new javax.swing.JLabel();
        jLabelJ4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setText("Turno del jugador Rojo");

        dadosbtn.setText("Tirar dados");
        dadosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosbtnActionPerformed(evt);
            }
        });

        LabelJ1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        LabelJ1.setText("Jugador Rojo: 0");

        LabelJ2.setText("Jugador Amarillo: 0");

        jLabelJ3.setText("Jugador Verde: 0");

        jLabelJ4.setText("Jugador Azul: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJ2)
                            .addComponent(LabelJ1)
                            .addComponent(jLabelJ3)
                            .addComponent(jLabelJ4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(dadosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelJ1)
                .addGap(18, 18, 18)
                .addComponent(LabelJ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelJ3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelJ4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(dadosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosbtnActionPerformed
        // TODO add your handling code here:
        jLabelJ3.setVisible(true);
        int dadoJ1 = 0, dadoJ2 = 0, dadoJ3 = 0, dadoJ4 = 0;
        int dado1 = (int) ((Math.random()) * 60 / 10) + 1;//dado 1
        int dado2 = (int) ((Math.random()) * 60 / 10) + 1;//dado2
        int dado = dado1 + dado2;
        dados(dado1, dado2);
        switch (turno) {
            case 1:
                dadoJ1 = dado;
                LabelJ1.setText("Jugador Rojo: " + dado);
                Titulo.setText("Turno del jugador Amarillo");
                break;
                
            case 2:
                dadoJ2 = dado;
                LabelJ2.setText("Jugador Amarillo: " + dado);
                Titulo.setText("Turno del jugador Verde");
                break;
            case 3:
                dadoJ3 = dado;
                jLabelJ3.setText("Jugador Verde: " + dado);
                Titulo.setText("Turno del jugador Azul");
                break;
            case 4:
                dadoJ4 = dado;
                jLabelJ4.setText("Jugador Azul: " + dado);
                break;
        }
        turno++;

        //Hacer validación si son iguales
        if (turno > Variables.njugadores) {
            JOptionPane.showMessageDialog(null, "Hola", "DADOS", JOptionPane.PLAIN_MESSAGE);
            switch (Variables.njugadores) {
                case 2:
                    if (dadoJ1 > dadoJ2) {
                        Variables.jugador1.turno = 1;
                    } else {
                        Variables.jugador2.turno = 2;
                    }
                    this.dispose();
                    break;
                case 3:
                    /*//List<Integer> posiciones = Arrays.asPosiciones(dadoJ1,dadoJ2,dadoJ3);
                    ArrayList<Integer> posiciones1 = new ArrayList<Integer>();
                    posiciones1.add(dadoJ1);
                    System.out.println("dado1: "+ dadoJ1);
                    posiciones1.add(dadoJ2);
                    System.out.println(dadoJ2);
                    posiciones1.add(dadoJ3);
                    System.out.println(dadoJ3);
                    Collections.sort(posiciones1);
                    
                    for(Integer numero : posiciones1){
                        System.out.println(numero);
                    }*/
                    if(dadoJ1> dadoJ2 && dado1>dadoJ3){
                        Variables.jugador1.turno = 1;
                        if(dadoJ2> dadoJ3){
                            Variables.jugador2.turno = 2;
                            Variables.jugador3.turno = 3;
                        }else{
                            Variables.jugador2.turno = 3;
                            Variables.jugador3.turno = 2;
                        }
                    }
                    if(dadoJ2>dadoJ1 && dadoJ2>dadoJ3){
                        Variables.jugador2.turno = 1;
                        if(dadoJ1>dadoJ3){
                            Variables.jugador1.turno = 2;
                            Variables.jugador3.turno = 3;
                        }else{
                            Variables.jugador1.turno = 3;
                            Variables.jugador3.turno = 2;
                        }
                    }
                    if(dadoJ3>dadoJ1 && dadoJ3>dadoJ2){
                        Variables.jugador3.turno = 1;
                        if(dadoJ1>dadoJ2){
                            Variables.jugador1.turno = 2;
                            Variables.jugador2.turno = 3;
                        }else{
                            Variables.jugador1.turno = 3;
                            Variables.jugador2.turno = 2;
                        }
                    }
                    System.out.println("J1 "+Variables.jugador1.turno);
                    System.out.println("J2 "+Variables.jugador2.turno);
                    System.out.println("J3 "+Variables.jugador3.turno);
                    break;
                case 4:
                     ArrayList<Integer> posiciones2 = new ArrayList<Integer>();
                    posiciones2.add(dadoJ1);
                    posiciones2.add(dadoJ2);
                    posiciones2.add(dadoJ3);
                    posiciones2.add(dadoJ4);
                    
                    Collections.sort(posiciones2);
                    for(Integer numero : posiciones2){
                        System.out.println(numero);
                    }
                    break;
            }

        }

    }//GEN-LAST:event_dadosbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugarMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugarMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugarMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugarMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JugarMayor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelJ1;
    private javax.swing.JLabel LabelJ2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton dadosbtn;
    private javax.swing.JLabel jLabelJ3;
    private javax.swing.JLabel jLabelJ4;
    // End of variables declaration//GEN-END:variables
    public void dados(int dado1, int dado2) {
        ImageIcon icono = null;

        switch (dado1) { // ver las combinaciones 
            case 1:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/1,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/1,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/1,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/1,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/1,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/1,6.png"));
                        break;
                }
                break;
            case 2:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/2,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/2,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/2,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/2,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/2,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/2,6.png"));
                        break;
                }
                break;
            case 3:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/3,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/3,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/3,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/3,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/3,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/3,6.png"));
                        break;
                }
                break;
            case 4:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/4,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/4,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/4,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/4,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/4,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/4,6.png"));
                        break;
                }
                break;
            case 5:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/5,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/5,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/5,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/5,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/5,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/5,6.png"));
                        break;
                }
                break;
            case 6:
                switch (dado2) {
                    case 1:
                        icono = new ImageIcon(getClass().getResource("/dados/6,1.png"));
                        break;
                    case 2:
                        icono = new ImageIcon(getClass().getResource("/dados/6,2.png"));
                        break;
                    case 3:
                        icono = new ImageIcon(getClass().getResource("/dados/6,3.png"));
                        break;
                    case 4:
                        icono = new ImageIcon(getClass().getResource("/dados/6,4.png"));
                        break;
                    case 5:
                        icono = new ImageIcon(getClass().getResource("/dados/6,5.png"));
                        break;
                    case 6:
                        icono = new ImageIcon(getClass().getResource("/dados/6,6.png"));
                        break;
                }
                break;
        }
        JOptionPane.showMessageDialog(null, "", "DADOS", JOptionPane.PLAIN_MESSAGE, icono);
    }

}
